### ISSUE TITLE
Contrato_Café Huerto el Mamey

### ISSUE THREAD

**Issue by Edwin-1012** [SistemasTecTlaxiaco/contrato-de-software-entrevista-gp#1]
[Contrato_Finalizado_Café Huerto el Mamey_Edwin, Taoli, Alexis, Iván.pdf](https://github.com/SistemasTecTlaxiaco/contrato-de-software-entrevista-gp/files/7741940/Contrato_Finalizado_Cafe.Huerto.el.Mamey_Edwin.Taoli.Alexis.Ivan.pdf)

**Comment by MaGuadalupeQuiroz** [comment]
Calificación 20%
Buen trabajo, la redacción es clara y contiene todos los puntos claves.

**Comment by MaGuadalupeQuiroz** [comment]
Calificación Wiki 80%
Wiki correctamente documentada con todos los puntos necesarios

**Comment by josealfredo79** [comment]
esta bien hecho y revisado
